version: '3.7'

services:
  front:
    build:
      target: development
      args:
        EPIC_ROAD_TRIP_INTERNAL_API_URL: ${EPIC_ROAD_TRIP_INTERNAL_API_URL}
    environment:
      EPIC_ROAD_TRIP_INTERNAL_API_URL: ${EPIC_ROAD_TRIP_INTERNAL_API_URL}
    volumes:
      - /usr/src/front/node_modules
      - ./front:/usr/src/front

  back:
    build:
      target: development
    volumes:
      - /usr/src/back/node_modules
      - ./back:/usr/src/back

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:5.1
    links:
      - sql:db
    ports:
      - 34003:80
    depends_on:
      - sql
